version: "3.9"

services:
  openmc:
    build:
      context: .
      dockerfile: OpenMC/Dockerfile
    volumes:
      - ../OmniFlow/:/OmniFlow/
      - /tmp/:/tmp/
    tty: true
    stdin_open: true



# docker compose -f "docker-compose-openmc.yml" build
# docker compose -f "docker-compose-openmc.yml" up